# Generated by Django 5.1.5 on 2025-05-01 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_alter_article_header_image_articleimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_on'], 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.RenameField(
            model_name='articleimage',
            old_name='recipe',
            new_name='article',
        ),
    ]
