# Generated by Django 5.1.6 on 2025-05-10 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_article_category_alter_article_title_and_more'),
        ('blog', '0003_articleimage'),
    ]

    operations = [
    ]
