# Generated by Django 5.1.5 on 2025-05-12 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_merge_20250513_0013'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticleImage',
        ),
    ]
