# Generated by Django 5.1.5 on 2025-05-12 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Product Type',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, default=1, max_digits=100)),
                ('stock', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('ON_SALE', 'On sale'), ('NO_STOCK', 'Out of stock')], default='AVAILABLE', max_length=255)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='user_management.profile')),
                ('productType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='merchstore.producttype')),
            ],
            options={
                'verbose_name': 'Product',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=1)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('IN_CART', 'On cart'), ('TO_PAY', 'To pay'), ('TO_SHIP', 'To ship'), ('TO_RECEIVE', 'To receive'), ('DELIVERED', 'Delivered')], max_length=255, null=True)),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='user_management.profile')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='merchstore.product')),
            ],
            options={
                'verbose_name': 'Transaction',
                'ordering': ['buyer', 'created_on'],
            },
        ),
    ]
