# Generated by Django 5.1.5 on 2025-05-13 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchstore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('On sale', 'On sale'), ('Out of stock', 'Out of stock')], default='AVAILABLE', max_length=255),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('On cart', 'On cart'), ('To pay', 'To pay'), ('To ship', 'To ship'), ('To receive', 'To receive'), ('Delivered', 'Delivered')], max_length=255, null=True),
        ),
    ]
