# Generated by Django 5.1.6 on 2025-04-25 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchstore', '0002_product_status_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('ON_SALE', 'On sale'), ('NO_STOCK', 'Out of stock')], default='AVAILABLE', max_length=255),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('ON_CART', 'On cart'), ('TO_PAY', 'To pay'), ('TO_SHIP', 'To ship'), ('TO_RECEIVE', 'To receive'), ('DELIVERED', 'Delivered')], max_length=255, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='merchstore.product')),
            ],
        ),
    ]
