# Generated by Django 5.1.6 on 2025-03-03 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0003_alter_comment_commission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created'], 'verbose_name': 'Commission'},
        ),
        migrations.AlterModelOptions(
            name='commission',
            options={'ordering': ['created'], 'verbose_name': 'Commission'},
        ),
    ]
