# Generated by Django 5.1.6 on 2025-03-03 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0005_alter_comment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created'], 'verbose_name': 'Comment'},
        ),
    ]
