# Generated by Django 5.1.6 on 2025-04-27 07:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0007_alter_comment_commission'),
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commission',
            options={'ordering': ['created'], 'verbose_name': 'Commissions'},
        ),
        migrations.RemoveField(
            model_name='commission',
            name='peopleRequired',
        ),
        migrations.AddField(
            model_name='commission',
            name='status',
            field=models.CharField(choices=[('A', 'Open'), ('B', 'Full'), ('C', 'Completed'), ('D', 'Discountinued')], default='A', max_length=1),
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.TextField(blank=True)),
                ('manpowerRequired', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('A', 'Open'), ('B', 'Full')], default='A', max_length=1)),
                ('commission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='commissions.commission')),
            ],
            options={
                'verbose_name': 'Comments',
                'ordering': ['status', '-manpowerRequired'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'Pending'), ('B', 'Accepted'), ('C', 'Rejected')], default='A', max_length=1)),
                ('appliedOn', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to='user_management.profile')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='commissions.job')),
            ],
            options={
                'verbose_name': 'Job Applications',
                'ordering': ['status', '-appliedOn'],
            },
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
