# Generated by Django 5.1.6 on 2025-04-27 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0008_alter_commission_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commission',
            options={'ordering': ['status', 'created'], 'verbose_name': 'Commissions'},
        ),
    ]
