# Generated by Django 5.1.6 on 2025-04-27 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0009_alter_commission_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commission',
            options={'ordering': ['status', 'created'], 'verbose_name': 'Commission'},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['status', '-manpowerRequired'], 'verbose_name': 'Job'},
        ),
        migrations.AlterModelOptions(
            name='jobapplication',
            options={'ordering': ['status', '-appliedOn'], 'verbose_name': 'Job Application'},
        ),
    ]
