# Generated by Django 5.1.6 on 2025-04-30 18:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0011_commission_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='manpowerRequired',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
